habittracker_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('habits/', include('habits.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('achievements/', include('achievements.urls')),
    path('about/', include('about.urls')),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.main_view, name='main')
]

profiles/urls.py
from django.urls import path
from profiles import views

urlpatterns = [
    path('', views.profileView, name='profile'),
    path('edit/', views.profile_edit_view, name='profile_edit'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class ProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100, blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True, verbose_name='Аватар')
    cover_image = models.ImageField(upload_to='covers/', blank=False, null=True)

    def __str__(self):
        return f'{self.user.username}'
    

profiles/forms.py
from django import forms
from profiles import models


class ProfileEditForm(forms.ModelForm):
    city = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите ваш город'}))

    class Meta:
        model = models.ProfileModel
        fields = ['city', 'avatar', 'cover_image']

profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ProfileEditForm
from .models import ProfileModel


@login_required
def profileView(request):
    profile, created = ProfileModel.objects.get_or_create(user=request.user)
    profile.refresh_from_db()
    return render(request, 'profiles/profile.html', {'profile': profile})

@login_required
def profile_edit_view(request):
    profile, created = ProfileModel.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = ProfileEditForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            # Перенаправляем на страницу профиля
            return redirect('profile')  # ← Это вызовет profileView с обновленными данными
    
    form = ProfileEditForm(instance=profile)

    context = {
        'profile': profile,
        'user': request.user,
        'form': form,
        'request': request
    }

    return render(request, 'profiles/profile.html', context)

profiles/templates/profiles/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HabitTracker - Профиль</title>

    <link rel="icon" type="image/png" href="{% static 'img/иконка.png' %}">

    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <script src="{% static 'js/profile.js' %}"></script>
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'main' %}" class="logo">HabitTracker</a>
        <ul class="nav-links">
            <li><a href="{% url 'main' %}">Главная</a></li>
            <li><a href="{% url 'habits_list' %}">Привычки</a></li>
            <li><a href="{% url 'achievements' %}">Достижения</a></li>
            <li><a href="{% url 'about' %}">О нас</a></li>
            {% if user.is_authenticated %}
                <li class="profile-item">
                    <a href="{% url 'profile' %}" class="profile-link">
                        {% if profile.avatar %} 
                            <img src="{{ profile.avatar.url }}" alt="" 
                                style="width: 30px; height: 30px; border-radius: 50%; object-fit: cover; display: block;">
                        {% else %}
                            <div class="profile-avatar-link" style="width: 30px; height: 30px; border-radius: 50%; background: #000; color: white; display: flex; align-items: center; justify-content: center; font-weight: bold;">
                                {{ user.username|first }}
                            </div>
                        {% endif %}
                        <span class="profile-text">Профиль</span>
                    </a>
                </li>
            {% else %}
                <li><a href="{% url 'signin' %}">Войти</a></li>
            {% endif %}
        </ul>
    </nav>

    <div class="container">
        <div class="profile-header {% if profile.cover_image %}has-custom-cover{% endif %}" 
             {% if profile.cover_image %}style="background-image: url('{{ profile.cover_image.url }}')"{% endif %}>
        </div>
        
        <div class="block-profile-information">
            <div class="profile-avatar">
                {% if profile.avatar %}
                    <img src="{{ profile.avatar.url }}" alt="Аватар" style="width: 100%; height: 100%; border-radius: 50%; object-fit: cover;">
                {% else %}
                    {{ user.username|first }}
                {% endif %}
            </div>
            <div class="profile-username"><h1>{{ user.username }}</h1></div>
            <div class="profile-information-city-country"> г. {{ profile.city|default:"Не указан"}}</div>
            <button class="open-modal-btn" onclick="openModal()">Редактировать профиль</button>
        </div>
    </div>

    <div class="container">
        <div class="settings-content">
            <h2>Настройки</h2>
            <div class="settings-cards">
                <a href="https://t.me/habittracker_top_bot" class="settings-card" target="_blank">
                    <div class="settings-card-header">
                        <h3>Напоминания о привычках</h3>
                    </div>
                    <p>Подключите телеграмм бота чтобы не забывать выполнять привычки</p>
                </a>
            </div>
        </div>
    </div>
    
    <div class="modal-overlay" id="modalOverlay">
        <div class="modal">
            <div class="container">
                <form method="post" action="{% url 'profile_edit' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-header">
                        <h1>Редактировать профиль</h1>
                        <div class="modal-profile-header">
                            <div class="cover-container {% if profile.cover_image %}has-custom-cover{% endif %}" id="modal-cover" 
                                 {% if profile.cover_image %}style="background-image: url('{{ profile.cover_image.url }}')"{% endif %}>
                            </div>
                            
                            <div class="modal-profile-avatar" onclick="document.getElementById('avaInput').click()">
                                {% if profile.avatar %}
                                    <img src="{{ profile.avatar.url }}" alt="Аватар" style="width: 100%; height: 100%; border-radius: 50%; object-fit: cover;">
                                {% else %}
                                    <div class="avatar-letter">{{user.username|first}}</div>
                                {% endif %}
                            </div>
                            
                            <input type="file" name="avatar" id="avaInput" class="file-input" accept="image/*" onchange="showAva()">
                            <label for="coverInput" class="styled-file-button">
                                {% if profile.cover_image %}Сменить обложку{% else %}Выбрать обложку{% endif %}
                            </label>
                            <input type="file" 
                                   id="coverInput" 
                                   name="cover_image" 
                                   class="file-input" 
                                   accept="image/*"
                                   onchange="showCover()">
                        </div>
                    </div>
    
                    <div class="modal-body">
                        <div class="block-profile-information">
                            <div class="form-group">
                                <input type="text" 
                                    name="city" 
                                    class="form-control" 
                                    id="id_city"
                                    placeholder="Введите ваш город"
                                    value="{{ profile.city }}"
                                    style="width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 4px;">
                            </div>
                        </div>
                    </div>
    
                    <div class="modal-footer">
                        <button type="button" class="btn-secondary" onclick="closeModal()">Закрыть</button>
                        <button type="submit" class="btn-primary">Сохранить</button>
                    </div>  
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="logout-block">
            <a href="{% url 'logout' %}" class="logout">
                Выйти
            </a>
        </div>
    </div>
</body>
</html>
    